### ISSUE TITLE
PM_Meta coordinate Group 3

### ISSUE THREAD

**Issue by maxschmi** [data-hydenv/PM_measurement#1]
The coordinates from group 3 (5001-C1A5) seem to be very wrong! Could you please look over them...
The first mesurement (point 0) is somewhere near Stegen.
The third mesurement (point 2) is somewhere in switzerland.

![grafik](https://user-images.githubusercontent.com/46047581/51552711-784d9980-1e71-11e9-9e7e-5ebbead848da.png)

**Comment by PhilJd** [comment]
Fixed with the new meta table :)
