### ISSUE TITLE
Time serie

### ISSUE THREAD

**Issue by maxschmi** [data-hydenv/PM_measurement#2]
in the database-table "pm_data" our measurements start at 11 o'clock but in reality we started at 12!
could some one check this please?

**Comment by mmaelicke** [comment]
Time zone...

Be sure what's used in the file and how the database ist set up. In case you use a *timestamp with time zone* datatype, but do not specify it, it will be utc.

**Comment by PhilJd** [comment]
The measurements start around 11:54 to 11:58  for me:
```
SELECT * from pm_data WHERE "Logger_id"='5002-11F6'
5002-11F6	0	2019-01-18 11:58:01	12.6	6.3
5002-11F6	0	2019-01-18 11:58:03	12.3	6.1
```

**Comment by maxschmi** [comment]
Ok probably it is just a problem how DataGrip shows the data. Maybe it transformed everything to UTC.
