### ISSUE TITLE
Provide all PM data

### ISSUE THREAD

**Issue by modche** [data-hydenv/PM_measurement#4]
As I see you set up a great teamwork here and organized to measure PM10/PM25 at many locations in Freiburg. 
It would be nice to have at the end of the module a data file with all the measured values (and date/time) and a linked meta file with the exact locations etc. So, i would really appreciate if some of you can organize to generate such files (e.g. next week, there is no hurry...)! 

Is this meta information valid? 
https://docs.google.com/spreadsheets/d/1FunjpDl0yrtSjr61oK9PetiVVcg_lu_XMqIA_0-wWwI/edit#gid=0

Is this _how-to_ OK? https://github.com/data-hydenv/PM_measurement/blob/master/Measurement_HOW-TO.pdf

Thank you all!!!

**Comment by maxschmi** [comment]
You find our final data on the Postgresql Database from the course. 
pm_meta and pm_measurement!

The How-to explains how we measured.

**Comment by mmaelicke** [comment]
I dumped the metadata and data into a CSV and uploaded to the [data](https://github.com/data-hydenv/data) repository. See commit [#3faffa](https://github.com/data-hydenv/data/commit/3faffa).
The files are named pm_data_2019.csv and pm_metadata_2019.csv

I will close this issue.
